version: "3"

services:
  mongo:
    image: mongo:3.6
    restart: always
    ports:
      - "27017:27017"

  redis:
    image: redis:3
    restart: always
    ports:
      - "6379:6379"

  derby_site:
    image: derbyjs/derby-site:${DERBY_SITE_TAG}
    restart: always
    ports:
      - "4000:4000" 
    labels:
      traefik.enable: true
      traefik.frontend.rule: Host:derbyjs.com,www.derbyjs.com

  derby_examples:
    image: derbyjs/derby-examples:${DERBY_EXAMPLES_TAG}
    restart: always
    ports:
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
      - "8004:8004"
      - "8005:8005"
      - "8006:8006"
      - "8007:8007"
      - "8008:8008"
      - "8009:8009"
    environment:
      MONGO_HOST: mongo
      REDIS_HOST: redis
    labels:
      traefik.enable: true
      traefik.charts.frontend.rule: Host:charts.derbyjs.com
      traefik.charts.port: 8001
      traefik.chat.frontend.rule: Host:chat.derbyjs.com
      traefik.chat.port: 8002
      traefik.codemirror.frontend.rule: Host:codemirror.derbyjs.com
      traefik.codemirror.port: 8003
      traefik.directory.frontend.rule: Host:directory.derbyjs.com
      traefik.directory.port: 8004
      traefik.hello.frontend.rule: Host:hello.derbyjs.com
      traefik.hello.port: 8005
      traefik.sink.frontend.rule: Host:sink.derbyjs.com
      traefik.sink.port: 8006
      traefik.todos.frontend.rule: Host:todos.derbyjs.com
      traefik.todos.port: 8007
      traefik.widgets.frontend.rule: Host:widgets.derbyjs.com
      traefik.widgets.port: 8008
      traefik.render.frontend.rule: Host:render.derbyjs.com
      traefik.render.port: 8009

  traefik:
    image: traefik:1.6-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports: 
      - "0.0.0.0:8181:8080"
      - "0.0.0.0:8080:80"
    command:
      - --api=true
      - --docker
      - --docker.exposedbydefault=false

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/derbyjs.conf:/etc/nginx/conf.d/derbyjs.conf
    ports:
      - "0.0.0.0:8180:80"
    command: /bin/bash -c "nginx -g 'daemon off;'"

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
      com.docker.network.driver.mtu: "1500"
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"